[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = ['cd backend && npm ci --production']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'cd backend && node server.js'
